width = 100%
height = 100%
border-width = 0
outline-width = 0
padding-top = 33%
padding-left = 10%
padding-right = 10%
result-spacing = 25
num-results = 5

font = JetBrainsMono Nerd Font
font-size = 24

text-color = #c0caf5
prompt-text = " : "
background-color = #1a1b26d9
selection-color = #7aa2f7
