#!/usr/bin/env python3
"""
Generate security audit reports from VULNERABILITIES.json.
Usage: python3 generate_report.py /path/to/project [--format markdown|json|sarif]
"""

import sys
import json
from pathlib import Path
from datetime import datetime
from typing import Optional


def load_vulnerabilities(project_path: Path) -> Optional[dict]:
    """Load vulnerabilities from JSON file."""
    vuln_file = project_path / '.security-audit' / 'VULNERABILITIES.json'
    
    if not vuln_file.exists():
        return None
    
    try:
        return json.loads(vuln_file.read_text())
    except Exception as e:
        print(f"Error loading vulnerabilities: {e}")
        return None


def severity_emoji(severity: str) -> str:
    """Get emoji for severity level."""
    return {
        'critical': '🔴',
        'high': '🟠',
        'medium': '🟡',
        'low': '🟢',
    }.get(severity.lower(), '⚪')


def severity_badge(severity: str) -> str:
    """Get text badge for severity."""
    return f"**{severity.upper()}**"


def generate_markdown_report(data: dict, project_name: str) -> str:
    """Generate Markdown report."""
    vulns = data.get('vulnerabilities', [])
    
    # Count by severity
    counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0}
    for v in vulns:
        sev = v.get('severity', 'low').lower()
        counts[sev] = counts.get(sev, 0) + 1
    
    total = len(vulns)
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    # Determine overall risk
    if counts['critical'] > 0:
        overall_risk = 'Critical'
    elif counts['high'] > 0:
        overall_risk = 'High'
    elif counts['medium'] > 0:
        overall_risk = 'Medium'
    else:
        overall_risk = 'Low'
    
    report = f"""# Security Audit Report

**Project:** {project_name}  
**Date:** {timestamp}  
**Generated by:** Claude Security Audit Skill

---

## Executive Summary

### Overview
Automated security audit performed using multi-phase analysis including architecture assessment, STRIDE threat modeling, and code review with evidence validation.

### Key Findings

| Severity | Count |
|----------|-------|
| {severity_emoji('critical')} Critical | {counts['critical']} |
| {severity_emoji('high')} High | {counts['high']} |
| {severity_emoji('medium')} Medium | {counts['medium']} |
| {severity_emoji('low')} Low | {counts['low']} |
| **Total** | **{total}** |

### Overall Risk Level: **{overall_risk}**

---

## Detailed Findings

"""
    
    # Sort vulnerabilities by severity
    severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3}
    sorted_vulns = sorted(vulns, key=lambda x: severity_order.get(x.get('severity', 'low').lower(), 4))
    
    for i, vuln in enumerate(sorted_vulns, 1):
        vuln_id = vuln.get('id', f'VULN-{i:03d}')
        title = vuln.get('title', 'Untitled Vulnerability')
        severity = vuln.get('severity', 'low')
        cwe = vuln.get('cwe_id', 'N/A')
        cvss = vuln.get('cvss_score', 'N/A')
        file_path = vuln.get('file_path', 'Unknown')
        line_num = vuln.get('line_number', '')
        
        location = f"`{file_path}"
        if line_num:
            location += f":{line_num}"
        location += "`"
        
        report += f"""### {vuln_id}: {title}

| Attribute | Value |
|-----------|-------|
| **Severity** | {severity_emoji(severity)} {severity.upper()} |
| **CWE** | {cwe} |
| **CVSS** | {cvss} |
| **Location** | {location} |
| **Exploitability** | {vuln.get('exploitability', 'Unknown')} |

#### Description
{vuln.get('description', 'No description provided.')}

"""
        
        if vuln.get('code_snippet'):
            report += f"""#### Vulnerable Code
```
{vuln.get('code_snippet')}
```

"""
        
        if vuln.get('evidence'):
            report += f"""#### Evidence
{vuln.get('evidence')}

"""
        
        if vuln.get('attack_vector'):
            report += f"""#### Attack Vector
{vuln.get('attack_vector')}

"""
        
        if vuln.get('recommendation'):
            report += f"""#### Recommendation
{vuln.get('recommendation')}

"""
        
        if vuln.get('references'):
            report += "#### References\n"
            for ref in vuln.get('references', []):
                report += f"- {ref}\n"
            report += "\n"
        
        report += "---\n\n"
    
    # Recommendations summary
    report += """## Recommendations Summary

### Immediate Actions (Critical/High)
"""
    
    critical_high = [v for v in sorted_vulns if v.get('severity', '').lower() in ['critical', 'high']]
    for i, v in enumerate(critical_high, 1):
        report += f"{i}. [ ] Fix {v.get('title', 'issue')} in `{v.get('file_path', 'unknown')}`\n"
    
    if not critical_high:
        report += "No critical or high severity issues found.\n"
    
    report += """
### Medium Priority
"""
    
    medium = [v for v in sorted_vulns if v.get('severity', '').lower() == 'medium']
    for i, v in enumerate(medium, 1):
        report += f"{i}. [ ] Address {v.get('title', 'issue')}\n"
    
    if not medium:
        report += "No medium severity issues found.\n"
    
    report += f"""
---

## Appendix

### Scan Statistics
- **Files Analyzed:** {data.get('scan_stats', {}).get('files_analyzed', 'N/A')}
- **Threats Modeled:** {data.get('scan_stats', {}).get('threats_validated', 'N/A')}
- **Vulnerabilities Confirmed:** {total}

### Methodology
1. **Phase 1 - Assessment:** Architecture and data flow mapping
2. **Phase 2 - Threat Modeling:** STRIDE-based threat identification
3. **Phase 3 - Code Review:** Vulnerability validation with evidence
4. **Phase 4 - Reporting:** Findings compilation and prioritization

---

*Report generated by Claude Security Audit Skill*
*Timestamp: {timestamp}*
"""
    
    return report


def generate_json_report(data: dict, project_name: str) -> str:
    """Generate JSON report."""
    vulns = data.get('vulnerabilities', [])
    
    counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0}
    for v in vulns:
        sev = v.get('severity', 'low').lower()
        counts[sev] = counts.get(sev, 0) + 1
    
    report = {
        'metadata': {
            'project': project_name,
            'generated': datetime.now().isoformat(),
            'version': '1.0.0',
            'generator': 'Claude Security Audit Skill'
        },
        'summary': {
            'total_vulnerabilities': len(vulns),
            'by_severity': counts,
            'overall_risk': 'critical' if counts['critical'] > 0 else 
                           'high' if counts['high'] > 0 else
                           'medium' if counts['medium'] > 0 else 'low'
        },
        'vulnerabilities': vulns,
        'scan_stats': data.get('scan_stats', {})
    }
    
    return json.dumps(report, indent=2)


def generate_sarif_report(data: dict, project_name: str) -> str:
    """Generate SARIF format report for CI/CD integration."""
    vulns = data.get('vulnerabilities', [])
    
    severity_to_level = {
        'critical': 'error',
        'high': 'error',
        'medium': 'warning',
        'low': 'note'
    }
    
    results = []
    for vuln in vulns:
        result = {
            'ruleId': vuln.get('cwe_id', 'UNKNOWN'),
            'level': severity_to_level.get(vuln.get('severity', 'low').lower(), 'note'),
            'message': {
                'text': f"{vuln.get('title', 'Vulnerability')}: {vuln.get('description', '')}"
            },
            'locations': [
                {
                    'physicalLocation': {
                        'artifactLocation': {
                            'uri': vuln.get('file_path', 'unknown')
                        },
                        'region': {
                            'startLine': vuln.get('line_number', 1)
                        }
                    }
                }
            ]
        }
        results.append(result)
    
    sarif = {
        '$schema': 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
        'version': '2.1.0',
        'runs': [
            {
                'tool': {
                    'driver': {
                        'name': 'Claude Security Audit',
                        'version': '1.0.0',
                        'informationUri': 'https://claude.ai'
                    }
                },
                'results': results
            }
        ]
    }
    
    return json.dumps(sarif, indent=2)


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_report.py /path/to/project [--format markdown|json|sarif]")
        sys.exit(1)
    
    project_path = Path(sys.argv[1]).resolve()
    
    # Parse format argument
    output_format = 'markdown'
    if '--format' in sys.argv:
        idx = sys.argv.index('--format')
        if idx + 1 < len(sys.argv):
            output_format = sys.argv[idx + 1].lower()
    
    # Load vulnerabilities
    data = load_vulnerabilities(project_path)
    
    if not data:
        print(f"Error: No VULNERABILITIES.json found in {project_path}/.security-audit/")
        print("Run the security audit first to generate vulnerability data.")
        sys.exit(1)
    
    project_name = project_path.name
    
    # Generate report
    if output_format == 'json':
        report = generate_json_report(data, project_name)
        output_file = project_path / '.security-audit' / 'scan_results.json'
    elif output_format == 'sarif':
        report = generate_sarif_report(data, project_name)
        output_file = project_path / '.security-audit' / 'scan_results.sarif'
    else:
        report = generate_markdown_report(data, project_name)
        output_file = project_path / '.security-audit' / 'scan_report.md'
    
    # Write report
    output_file.write_text(report)
    print(f"Report generated: {output_file}")
    
    # Also print to stdout
    print("\n" + "="*60)
    print(report)


if __name__ == '__main__':
    main()
