source = $HOME/.config/hypr/colors.conf

general {
    ignore_empty_input = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    color = $base
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $surface0
    outer_color = $text
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = $text
    font_size = 18

    placeholder_text = Enter Password
    check_color = $accent
    fail_color = $red
    fail_text = $FAIL ($ATTEMPTS)

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}
