background = #000000
foreground = #ffffff
cursor-color = #6366f1
selection-background = #3b3a8a
selection-foreground = #ffffff

palette = 0=#404040
palette = 1=#a4a4a4
palette = 2=#b6b6b6
palette = 3=#fcd34d
palette = 4=#6366f1
palette = 5=#9b9b9b
palette = 6=#b0b0b0
palette = 7=#ececec
palette = 8=#fdfdfd
palette = 9=#a4a4a4
palette = 10=#b6b6b6
palette = 11=#fde68a
palette = 12=#818cf8
palette = 13=#9b9b9b
palette = 14=#b0b0b0
palette = 15=#ffffff
