# Tokyo Night — p10k + zsh-autosuggestions

POWERLEVEL9K_DIR_FOREGROUND='#7aa2f7'
POWERLEVEL9K_VCS_FOREGROUND='#9ece6a'
POWERLEVEL9K_VCS_INCOMING_CHANGESFORMAT_FOREGROUND='#7dcfff'
POWERLEVEL9K_VCS_OUTGOING_CHANGESFORMAT_FOREGROUND='#7dcfff'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#e0af68'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='#565f89'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#bb9af7'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#bb9af7'
POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND='#bb9af7'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#f7768e'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND='#f7768e'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND='#f7768e'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#3b4261'
