# Vantablack: dark theme — p10k + zsh-autosuggestions
# Accent palette: #000000 bg / #ffffff fg / #8d8d8d accent / #cecece accent2 / #6366f1 indigo

POWERLEVEL9K_DIR_FOREGROUND='#8d8d8d'
POWERLEVEL9K_VCS_FOREGROUND='#6366f1'
POWERLEVEL9K_VCS_INCOMING_CHANGESFORMAT_FOREGROUND='#818cf8'
POWERLEVEL9K_VCS_OUTGOING_CHANGESFORMAT_FOREGROUND='#818cf8'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#8d8d8d'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='#8d8d8d'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#6366f1'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#6366f1'
POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND='#6366f1'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#a4a4a4'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND='#a4a4a4'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND='#a4a4a4'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#404040'
