# White: light theme — p10k + zsh-autosuggestions
# Accent palette: #ffffff bg / #000000 fg / #6e6e6e accent / #3a3a3a accent2

POWERLEVEL9K_DIR_FOREGROUND='#6e6e6e'
POWERLEVEL9K_VCS_FOREGROUND='#3a3a3a'
POWERLEVEL9K_VCS_INCOMING_CHANGESFORMAT_FOREGROUND='#6e6e6e'
POWERLEVEL9K_VCS_OUTGOING_CHANGESFORMAT_FOREGROUND='#6e6e6e'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#6e6e6e'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='#6e6e6e'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#000000'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#000000'
POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND='#000000'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#1a1a1a'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND='#1a1a1a'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND='#1a1a1a'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#c0c0c0'
